openapi: "3.0.2"
info:
  title: Otter Framework API
  version: "1.0"
  license:
    name: Apache 2.0
    url: https://spdx.org/licenses/Apache-2.0.html
  description: |
    The Otter Framework REST API is for API consumers to create and manipulate peer to peer video communication room resources.

    # Errors

    The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:

    ```
    {
      "message": "resource not found"
    }
    ```
servers:
  - url: http://localhost:3000/v1
security: []
paths:
  /rooms:
    post:
      summary: Create a new room
      operationId: createNewRoom
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
  /room/{id}:
    get:
      summary: Fetch a Room resource
      description: Fetch a specific Room resource by roomId
      operationId: getRoomById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  roomId:
                    type: string
                  status:
                    type: string
                    enum:
                      - "closed"
                      - "open"
                      - "occupied"
                      - "full"
                  createdAt:
                    type: string
                  updatedAt:
                    type: string
                  roomName:
                    type: string
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example: { message: "Room resource doesn't exist" }
