openapi: "3.0.2"
info:
  title: Otter Core API
  version: "1.0"
servers:
  - url: https://localhost:3000/v1
security: []
paths:
  /rooms:
    post:
      summary: Create a new room
      operationId: createNewRoom
      responses:
        "200":
          description: OK
